# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileView = QtWidgets.QListView(self.centralwidget)
        self.fileView.setGeometry(QtCore.QRect(10, 40, 271, 631))
        self.fileView.setObjectName("fileView")
        self.V_line1 = QtWidgets.QFrame(self.centralwidget)
        self.V_line1.setGeometry(QtCore.QRect(293, 0, 20, 751))
        self.V_line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.V_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.V_line1.setObjectName("V_line1")
        self.mainText = QtWidgets.QTextEdit(self.centralwidget)
        self.mainText.setGeometry(QtCore.QRect(320, 40, 741, 631))
        self.mainText.setObjectName("mainText")
        self.project_name = QtWidgets.QLineEdit(self.centralwidget)
        self.project_name.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.project_name.setObjectName("project_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.menu.addAction(self.action_1)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_3)
        self.menu_4.addAction(self.action_7)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "窗口"))
        self.menu_4.setTitle(_translate("MainWindow", "视图"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.action_1.setText(_translate("MainWindow", "新建"))
        self.action_2.setText(_translate("MainWindow", "打开"))
        self.action_4.setText(_translate("MainWindow", "保存"))
        self.action_5.setText(_translate("MainWindow", "另存为"))
        self.action_6.setText(_translate("MainWindow", "设置"))
        self.action_3.setText(_translate("MainWindow", "账户设置"))
        self.action_7.setText(_translate("MainWindow", "自动换行"))
